### ISSUE TITLE
ixbrl-viewer issue on negative values

### ISSUE THREAD

**Issue by freemaceo** [Workiva/ixbrl-viewer#199]
Hi, folks!

We found small Bug in iXBRLViewerPlugin. When we point on a negative value, the pointer does not change and we cannot click. 
In fact the span inline container do not markup correctly number starting with ‘-‘ and do not envelope correctly the inline element ‘ixbrl-element-nonfractional’. In this case the text inline element cannot manipulated with JavaScript function selectElementByClick().

Can you please help fixing this issue?

Regards,
Mahdi

**Comment by huizarmx** [comment]
According to the ixbrl spec, the number should not contain the minus sign, and the item should have the attribute sign="-"

See example below:

`<ix:nonfraction contextref="Cd3922568-78b1-47a8-fab5-8ec1bca51799" unitref="Ua8e2e75a-3d26-45ae-8987-f0beacfe31f7" name="ifrs-full:GainsLossesOnExchangeDifferencesOnTranslationNetOfTax" format="ixt:numdotdecimal" decimals="-3" sign="-" id="ixv-160">1,285,000</ix:nonfraction>`

**Comment by freemaceo** [comment]
Thanks for the explanation but we have the following: The number do not contain a minus and the attribute sign is there:
``								<span class="dmspan dmtext006" style="font-size:8pt; left:31.22pt; top:3.76pt; line-height:8pt;">‑<ix:nonFraction name="unicreditbankag:NegativeInterestOnFinancialAssets" contextRef="PYTD" unitRef="EUR" decimals="-6" format="ixt:num-comma-decimal" scale="6" sign="-" id="ixv-3"> 154</ix:nonFraction></span>
								<span class="dmspan dmtext001" style="font-size:8pt; left:33.88pt; top:2.74pt;"> 154
								</span>``

**Comment by huizarmx** [comment]
I don't see the need to print the value of the fact outside the ix:nonFraction element. 

This is an example of how I render a negative numerical fact

`<td class="td-numerical-fact text-end ixbrl-element ixbrl-element-nonfraction ixbrl-selected"><div class="clearfix"><span class="float-end"><span>(</span><ix:nonfraction contextref="C1ab9c0cc-4ac3-4600-8fdc-19c83e8ca02e" unitref="U91d6cf78-f4bb-4a24-cd81-6523c9831cd8" name="ifrs-full:OtherComprehensiveIncomeThatWillBeReclassifiedToProfitOrLossNetOfTax" format="ixt:numdotdecimal" id="F6eda287e-e20b-46c9-d146-5a3e3ffe10b2" decimals="-3" sign="-">11,515,295,000</ix:nonfraction><span>)</span></span></div></td>`

In my case it's a monetary fact so, instead of the dash I want to present parenthesis. Hope this helps.

**Comment by freemaceo** [comment]
This is very helpful thank you @huizarmx
We will try this out and close this issue if it's fixed.
