### ISSUE TITLE
[REQUEST] Nice to have feature  - Table Export Button (ixbrl-viewer/iXBRLViewerPlugin)

### ISSUE THREAD

**Issue by RamkumarAlagupandian** [Workiva/ixbrl-viewer#308]
I like all the feature within inline viewer specifically on "**_Table Export_**". Requesting to add  preferred label text instead of standard label text in the exported excel report. In the new build I could see link role titles are added so I feel that while export the specific table system should identify the presentation link role and pull the preferred label text in the column A in each element(s). 

In addition to that, system should check preferred label role in each element and retrieve the text, in case there is no preferred  label assigned to the element then system should automatically pull the Standard labels. By this way we can see all information in the table to review to make sure user created the right labels. (Just to match with Draft to identify the issues) 

**Preferred Screen Shots -**

Expected Output
![image](https://user-images.githubusercontent.com/20823537/173179524-a318d8d2-31ee-4b68-9b69-35968e7f9b36.png)

**Suggestion** - **If you add toggle button in each tagged table to flip and see the element & preferred label text in the viewer itself. if you design that option then that would be a great feature from a reviewer prospective.** 

** Example screen shots -- **

![image](https://user-images.githubusercontent.com/20823537/173179375-b6b9dd45-7468-4d06-ac62-69f588b5defc.png)

Thanks in Advance. 

Looking forward to hearing for you.

@hefischer @paulwarren-wk

**Comment by brettkail-wk** [comment]
> I like all the feature within inline viewer specifically on "Table Export". Requesting to add preferred label text instead of standard label text in the exported excel report.

There can be multiple preferred labels in the presentation linkbase for different sections of the document.  Trying to use a heuristic to guess the intent doesn't seem great.  I guess it would be possible to use the singular preferred label from the presentation if there is one, but it's not clear what to do if there are multiple.

> Suggestion - If you add toggle button in each tagged table to flip and see the element & preferred label text in the viewer itself. if you design that option then that would be a great feature from a reviewer prospective.

This screenshot looks like a feature request for [the SEC viewer](https://github.com/arelle/EdgarRenderer) rather than the ixbrl-viewer?

**Comment by hefischer** [comment]
The screen shots look like EdgarRenderer, not ix viewer.  EdgarRenderer changes probably should be checked with SEC DERA (via StructuredData)

   Herm

**Comment by RamkumarAlagupandian** [comment]
@brettkail-wk  @hefischer  - Thanks for the response. 

I just added as a reference screenshots. My request all belongs into ixbrl-viewer. I requested two items. Refer below details for your reference.

1. Would it possible to add a preferred label text in the excel file which exported from iXBRL-Viewer.
2. We have a button called "Export Table" in ixbrl-viewer which helps to export the table into excel format. In that i am requesting to add additional column in html to add the preferred label to view the draft & taxonomy display label. This will help us to find the label issues in the viewer itself. 

I hope this answered your questions.

**Comment by RamkumarAlagupandian** [comment]
Hello Team,

Any updates ?

**Comment by brettkail-wk** [comment]
> 1. Would it possible to add a preferred label text in the excel file which exported from iXBRL-Viewer.

As mentioned, it's somewhat unclear to me which preferred label to use if there are multiple.  If we can agree on some reasonable heuristic (perhaps sort roleType definition strings and then use the first preferred label in presentation order?), then it seems reasonable to me.

> 2. We have a button called "Export Table" in ixbrl-viewer which helps to export the table into excel format. In that i am requesting to add additional column in html to add the preferred label to view the draft & taxonomy display label. This will help us to find the label issues in the viewer itself.

I do not use this feature myself, so I don't really have an opinion.

@paulwarren-wk Do you have any thoughts/opinions on any of this?

**Comment by RamkumarAlagupandian** [comment]
@paulwarren-wk - Did you get a chance to review my request ?

**Comment by paulwarren-wk** [comment]
I have the same question as @brettkail-wk .  "Preferred label" is an attribute that can be set on a presentation relationship to select a particular label for a concept.  A presentation tree may use different preferred labels in different places.  Neither the fact inspector nor the table export feature make use of the presentation tree, so I don't understand where they'd get the preferred label from.

In the example shown above, with the fact inspector showing "terse label", how should the fact inspector decide to show the terse label rather than anything else.

**Comment by sagesmith-wf** [comment]
re: @brettkail-wk @paulwarren-wk

> In the example shown above, with the fact inspector showing "terse label", how should the fact inspector decide to show the terse label rather than anything else.

I might not be fully understanding the problem, but would it be reasonable (if and only if there were multiple labels for a concept) to show a drop down of table roles before the label text? Working off of the screenshot provided by @RamkumarAlagupandian instead of

**Preferred Label Type** label

maybe something like this:

**Preferred Label Type** [label_role_dropdown] label

or even:

### Labels 
**label_role_1** label
**label_role_2** label2

**Comment by brettkail-wk** [comment]
@sagesmith-wf As I understand it, [the topic of this issue](https://github.com/Workiva/ixbrl-viewer/issues/308#issuecomment-1155081667) is changing the output of Excel export.  The challenge seems to be that there's no standard way to deterministically know which XBRL outline section(s) are correlated to which HTML tables.  I'm not sure how a dropdown in the UI would help with that.

**Comment by sagesmith-wf** [comment]
@brettkail-wk
> As I understand it, https://github.com/Workiva/ixbrl-viewer/issues/308#issuecomment-1155081667 is changing the output of Excel export. The challenge seems to be that there's no standard way to deterministically know which XBRL outline section(s) are correlated to which HTML tables. I'm not sure how a dropdown in the UI would help with that.

👍 yep, I hadn't fully read through well enough. I agree with you and @paulwarren-wk . Going to close this issue for now
