### ISSUE TITLE
Highlights are shown correctly with an unexpected rectange

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#318]
Hi,

if you open the example and enable highlighting,
you can see an unexpected highlighted rectangle beneath the last 

It seems to happen when parts of the text are double tagged.

Here is the example: 
[Bug example.zip](https://github.com/Workiva/ixbrl-viewer/files/9400894/Bug.example.zip)

Kind regards,
Nachtino

**Comment by brettkail-wk** [comment]
The `dmspan` class is setting `white-space: pre`, and the span containing the word `column` contains a literal newline (lines 81-82), so the div is double tall.  The issue is resolved if the newline is removed (fixed [Bug.example.zip](https://github.com/Workiva/ixbrl-viewer/files/9403354/Bug.example.zip)).  The viewer appears to be working as expected.
