### ISSUE TITLE
[BUG] CSS position changing when adding the table export button

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/ixbrl-viewer#369]
### What happened?

The export table button is changing the underlining style of a document. The expectation would be that the export table button would not change the table position at all.

It might have something to do with [this](https://github.com/Workiva/ixbrl-viewer/blob/8c6b0c05d1ddc5e7b98cb98cc479392c8d4ca4e2/iXBRLViewerPlugin/viewer/src/js/tableExport.js#L30)

### Version

1.1.42

### With which browsers are you experiencing the bug?

Chrome

### Documents

[repro_filing_documents.zip](https://github.com/Workiva/ixbrl-viewer/files/10560698/a-2023-01-30-en.zip)
[generated_ixbrl_viewer_from_repro_docs.zip](https://github.com/Workiva/ixbrl-viewer/files/10560707/ixbrl_viewer.1.zip)

### Screenshots

![Untitled1](https://user-images.githubusercontent.com/17255946/216138996-2f6490d0-569d-423f-9015-33cbfea53900.png)

**Comment by paulwarren-wk** [comment]
I can see why this might occur, but I can't reproduce it with the provided sample.  This is what I see.  Without viewer:

![image](https://user-images.githubusercontent.com/45077928/216396878-fb6fe668-eafb-452d-a97a-45faa8ff8df6.png)

With viewer:

![image](https://user-images.githubusercontent.com/45077928/216396919-5ba547ab-894d-49b2-bc17-6f4e13f749a4.png)

**Comment by sagesmith-wf** [comment]
Let me follow up on this, its potentially been addressed

**Comment by paulwarren-wk** [comment]
I can't see a way to fix this using pure CSS, as we want to position the export control relative to the table's top-left, and in order to do that we need it to be `position:relative` which will unavoidably interfere with positioning a child of the table relative to a parent of the table.

One fix would be to make the export controls children of the body, calculate the position of the table, and place the handles accordingly using JS, but positions would need updating if the document was reflowed due to zoom or change in viewport size.

**Comment by sagesmith-wf** [comment]
It seems reasonable to not fix all of the document style changes. We should probably add the ability to download the original filing though if we aren't going to fix
