### ISSUE TITLE
[BUG] - Fact highlighting around text block tagging is too big

### ISSUE THREAD

**Issue by lukepint-wk** [Workiva/ixbrl-viewer#380]
### What happened?

Created a text block fact with a chart/image and the highlighting includes extra spacing causing it to overlap other content.

The fact highlighting should stop before the second graph in the screenshot.

### Version

1.1.44

### With which browsers are you experiencing the bug?

Chrome

### Documents

[wk-2023-02-09-en (1).zip](https://github.com/Workiva/ixbrl-viewer/files/10699899/wk-2023-02-09-en.1.zip)

### Screenshots

<img width="1117" alt="Screen Shot 2023-02-09 at 11 25 33 AM" src="https://user-images.githubusercontent.com/102554227/217890831-45f2ce68-61c1-4078-8364-1ffdabc2310e.png">

**Comment by paulwarren-wk** [comment]
Apologies - I was sure I'd replied to this one.  I think this an issue with  how the document is constructed, rather than the viewer.

Inside the relevant `ix:nonNumeric` is `div.positionStyle-60518f7f`.  This is absolutely positioned, so this is what we wrap the outline around, and it has a height of 570px.  This seems to be because it is inheriting a `line-height` of `285pt`.  If this `line-height` is removed, the size of this div shrinks to that of the `<span>` that it's wrapping, and the viewer highlighting also matches the image.

**Comment by lukepint-wk** [comment]
No worries! 

It appears you are correct! Thanks for looking into this. I raised the issue to the team responsible for the document construction and will close this.
