### ISSUE TITLE
[BUG] Number in table is not highlighted, table not exportable

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#442]
### What happened?

Hi,

Almost all tagged texts are also marked correctly, but there are a few exceptions. 
Open the attached file.
Look for table 'Ertragsteuern' -> Search for the number 1.650.

In addition, the table cannot be downloaded as an Excel file even it is a standard HTML <table>.

### Version

1.1.77

### With which browsers are you experiencing the bug?

Chrome

### Documents

[Example.zip](https://github.com/Workiva/ixbrl-viewer/files/11666376/Example.zip)

### Screenshots

![image](https://github.com/Workiva/ixbrl-viewer/assets/65947078/91e61935-0f46-4cd6-bca3-6fcf6c8a08c3)

**Comment by paulwarren-wk** [comment]
The issue here is that the HTML has an explicit background color on the numbers in the 2021 column, which overrides the background color that we use for highlighting.

I'm not sure how we could improve this.  We currently use classes to set the highlight color.  To override the explicit inline style on the element, we would need to use our own explicit inline style, but this would then require us to save the old style so that we could restore the original style when highlighting is turned off.

The table export feature is disabled because the table does not contain any numeric tags.  It is all enclosed within a single text block.

**Comment by paulwarren-wk** [comment]
Closing, as I can't see a way to improve this.
